### ISSUE TITLE
Upload same file again produces JS error

### ISSUE THREAD

**Issue by arkuuu** [flowjs/fusty-flow.js#13]
Hello,

I tried to auto-upload files after they are selected in the browser popup. I did this by using
```
flow.on('filesSubmitted', function (file) {
   console.debug(file);
   file[0].flowObj.upload(); // Start upload
 });
```
Note this is a single file upload only. Whenever I select a new file, it works flawlessly. But if I select the previously uploaded file again, it gives me
```
Uncaught TypeError: Cannot read property 'flowObj' of undefined
```
because `file` is empty.

What am I doing wrong? How can I allow the user to try to upload the same file again while keeping the auto-upload on selection?

**Comment by AidasK** [comment]
You should use an `if` statement to check if `file[0]` is defined. You can do it by writing `if (file.length > 0) {file[0].flowObj.upload();}`

**Comment by arkuuu** [comment]
Thanks. But what can I do if I really want to upload the same file again? Is this not possible?
