### ISSUE TITLE
initFileFn function not executed

### ISSUE THREAD

**Issue by djechelon** [flowjs/fusty-flow.js#21]
We use ng-flow a lot and have set our own custom file bootstrap function initFileFn in options to extend the file object with some method of ours.

I can see from the source code that Fusty's bootstrap function does not simply check for the existence of an initFileFn.

It it purposeful? Or can I just PR to add the same logic from flow.js?

Current

```
    bootstrap: function () {
      this.abort(true);
      this.finished = false;
      this.error = false;
},
```

Desired
```

    bootstrap: function () {
      if (typeof this.flowObj.opts.initFileFn === "function") {
        this.flowObj.opts.initFileFn(this);
      }

      this.abort(true);
      this.finished = false;
      this.error = false;
},
```

**Comment by AidasK** [comment]
Please open a pull request, fusty flow might be missing some new features
