### ISSUE TITLE
Headers do not appear to be getting set for request from iFrame

### ISSUE THREAD

**Issue by pjfreeze** [flowjs/fusty-flow.js#5]
I am using flow and falling back to fusty-flow for uploading images in an angularjs application, using ng-flow. I am providing the flow-init attribute the object specifying options and the header property with the keys and values I need set to support csrf auth.

Following is the object I provide the flow-init which following the code through shows it gets passed property to fusty flow:

```
$scope.initSettings = {
    headers: {
        'X-CSRFToken': Cookies.get('csrftoken'),
        'Authorization': $scope.user.getAuthToken()
    }
};
```

I've looked over https://github.com/flowjs/ng-flow/issues/82 and understand I need to set them for every request, but when viewing the request headers in IE9, the headers have not been set.

**Comment by AidasK** [comment]
For fusty flow you have to use query or post params to pass csrf token, because files are uploaded through iframe and there is no way you can set custom headers.

**Comment by pjfreeze** [comment]
@AidasK Thanks for the quick response.

**Comment by guymoyo** [comment]
thx, it works for me:

headers: function (file, chunk, isTest) {
                return {
                    'X-CSRF-TOKEN': $cookies.get("CSRF-TOKEN")// call func for getting a cookie
                }
            }
